image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

build_prod:
  stage: build
  script:
    - mv config.prod.json config.json
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE/prod" -f Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE/prod"
    - docker tag "$CI_REGISTRY_IMAGE/prod" "$CI_REGISTRY_IMAGE/prod:$CI_COMMIT_REF_NAME"
    - docker push "$CI_REGISTRY_IMAGE/prod:$CI_COMMIT_REF_NAME"
  only:
    - tags

build_integ:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE/integ" -f Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE/integ"
    - docker tag "$CI_REGISTRY_IMAGE/integ" "$CI_REGISTRY_IMAGE/integ:develop"
    - docker push "$CI_REGISTRY_IMAGE/integ:develop"
  only:
    - master

deploy_prod:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  script:
    - upgrade --environment default --stack ssz-prod --service stat --new-image $CI_REGISTRY_IMAGE/prod:$CI_COMMIT_REF_NAME
  only:
    - tags

deploy_integ:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  script:
    - upgrade --environment default --stack ssz-integ --service stat --new-image $CI_REGISTRY_IMAGE/integ:develop
  only:
    - master
